name: Daily Bot

on:
  workflow_dispatch:

  schedule:
    - cron: '0 0 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run Bot
        run: python bot.py
